// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqMO-uxmlnyePCjqbi_oB_l6LS-xVAAhg',
    appId: '1:1069918561797:web:4141266a1c4aabdedd1e6c',
    messagingSenderId: '1069918561797',
    projectId: 'flash-chat-eafa5',
    authDomain: 'flash-chat-eafa5.firebaseapp.com',
    storageBucket: 'flash-chat-eafa5.appspot.com',
    measurementId: 'G-0DT81GSS77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC05gmFzvZU49xcPTTlX_7T0TjJV1WKN0g',
    appId: '1:1069918561797:android:0b2bffc24878e534dd1e6c',
    messagingSenderId: '1069918561797',
    projectId: 'flash-chat-eafa5',
    storageBucket: 'flash-chat-eafa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_S2wS4AucjmoLXNisDO5ycpMXxNkAQI8',
    appId: '1:1069918561797:ios:1445e58e4c48387edd1e6c',
    messagingSenderId: '1069918561797',
    projectId: 'flash-chat-eafa5',
    storageBucket: 'flash-chat-eafa5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_S2wS4AucjmoLXNisDO5ycpMXxNkAQI8',
    appId: '1:1069918561797:ios:1445e58e4c48387edd1e6c',
    messagingSenderId: '1069918561797',
    projectId: 'flash-chat-eafa5',
    storageBucket: 'flash-chat-eafa5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqMO-uxmlnyePCjqbi_oB_l6LS-xVAAhg',
    appId: '1:1069918561797:web:67dab1a1d2c85d88dd1e6c',
    messagingSenderId: '1069918561797',
    projectId: 'flash-chat-eafa5',
    authDomain: 'flash-chat-eafa5.firebaseapp.com',
    storageBucket: 'flash-chat-eafa5.appspot.com',
    measurementId: 'G-SXHM0WZ311',
  );
}